insert into dealeat.tRestaurant([Name], Adresse, PhotoLink, Telephone, UserId) values('RestaurantName0', 'RestaurantAdresse0', 'RestaurantPhotoLink0', 0601020304, 0)
insert into dealeat.tRestaurant([Name], Adresse, PhotoLink, Telephone, UserId) values('RestaurantName1', 'RestaurantAdresse1', 'RestaurantPhotoLink1', 0604030201, 0);
insert into dealeat.tRestaurant([Name], Adresse, PhotoLink, Telephone, UserId) values('RestaurantName2', 'RestaurantAdresse2', 'RestaurantPhotoLink2', 0604030202, 0);
insert into dealeat.tRestaurant([Name], Adresse, PhotoLink, Telephone, UserId) values('RestaurantName3', 'RestaurantAdresse3', 'RestaurantPhotoLink3', 0604030203, 0);
insert into dealeat.tRestaurant([Name], Adresse, PhotoLink, Telephone, UserId) values('RestaurantName4', 'RestaurantAdresse4', 'RestaurantPhotoLink4', 0604030204, 0);
insert into dealeat.tRestaurant([Name], Adresse, PhotoLink, Telephone, UserId) values('RestaurantName5', 'RestaurantAdresse5', 'RestaurantPhotoLink5', 0604030205, 0);
insert into dealeat.tRestaurant([Name], Adresse, PhotoLink, Telephone, UserId) values('RestaurantName6', 'RestaurantAdresse6', 'RestaurantPhotoLink6', 0604030206, 0);
insert into dealeat.tRestaurant([Name], Adresse, PhotoLink, Telephone, UserId) values('RestaurantName7', 'RestaurantAdresse7', 'RestaurantPhotoLink7', 0604030207, 0);
insert into dealeat.tRestaurant([Name], Adresse, PhotoLink, Telephone, UserId) values('RestaurantName8', 'RestaurantAdresse8', 'RestaurantPhotoLink8', 0604030208, 0);